[project]
name = "game-info"
version = "0.1.0"
description = "A simple web-app to get information about Steam games."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.2",
    "numerize>=0.12",
    "requests>=2.32.5",
]
